In [6]:
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier 
from sklearn import tree



In [7]:
!pip install apyori
!pip install mlxtend --upgrade --no-deps
!pip install -U scikit-fuzzy

Requirement already up-to-date: mlxtend in /usr/local/lib/python3.7/dist-packages (0.18.0)
Requirement already up-to-date: scikit-fuzzy in /usr/local/lib/python3.7/dist-packages (0.4.2)


In [8]:
import numpy as np
import pandas as pd
from pandas import read_csv
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sn

from skfuzzy import control as ctrl
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
from __future__ import print_function
import numpy as np
from sklearn import datasets, linear_model



#def main():
#iris = datasets.load_iris()
df = read_csv("/content/discretised_dataset.csv")
print(type(df))
new_df=df.to_numpy()
print(new_df.shape)
print(type(new_df))
X=new_df[:,[1,2,3,4,5,6,7]]
print(X)
y=new_df[:,8]
print(y)
# Some noisy data not correlated
#E = np.random.uniform(0, 0.1, size=(len(iris.data), 20))






print(df)

<class 'pandas.core.frame.DataFrame'>
(299, 9)
<class 'numpy.ndarray'>
[[2 0 0 ... 1 1 0]
 [0 2 1 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 1 2 ... 0 2 2]
 [0 1 1 ... 1 0 2]
 [0 0 2 ... 1 2 2]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 1 0
 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1
 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0
 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
     Unnamed: 0  age_by_ds  ...  time_by_ds  DeathL
0             0          2  ...           0       1
1             1          0  ...           0       1
2             2          1  ...           0  

In [11]:
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier 
from sklearn import tree

# Prepare the data data
#iris = datasets.load_iris()
#X = iris.data
#y = iris.target

# Fit the classifier with max_depth=3
clf = DecisionTreeClassifier(max_depth=4, random_state=1234)
model = clf.fit(X, y)


In [12]:
# get the text representation
text_representation = tree.export_text(clf)
print(text_representation)

|--- feature_6 <= 0.50
|   |--- feature_3 <= 0.50
|   |   |--- feature_1 <= 0.50
|   |   |   |--- feature_4 <= 0.50
|   |   |   |   |--- class: 1
|   |   |   |--- feature_4 >  0.50
|   |   |   |   |--- class: 1
|   |   |--- feature_1 >  0.50
|   |   |   |--- feature_2 <= 1.50
|   |   |   |   |--- class: 1
|   |   |   |--- feature_2 >  1.50
|   |   |   |   |--- class: 0
|   |--- feature_3 >  0.50
|   |   |--- feature_2 <= 0.50
|   |   |   |--- feature_3 <= 1.50
|   |   |   |   |--- class: 1
|   |   |   |--- feature_3 >  1.50
|   |   |   |   |--- class: 0
|   |   |--- feature_2 >  0.50
|   |   |   |--- feature_3 <= 1.50
|   |   |   |   |--- class: 0
|   |   |   |--- feature_3 >  1.50
|   |   |   |   |--- class: 1
|--- feature_6 >  0.50
|   |--- feature_2 <= 0.50
|   |   |--- feature_4 <= 0.50
|   |   |   |--- feature_6 <= 1.50
|   |   |   |   |--- class: 1
|   |   |   |--- feature_6 >  1.50
|   |   |   |   |--- class: 0
|   |   |--- feature_4 >  0.50
|   |   |   |--- feature_5 <= 0.50
| 

In [13]:
import pandas as pd
feature_df = pd.read_csv("/content/discretised_dataset.csv")
keys=list(feature_df.keys())
new_key=keys[1:8]
target_key=keys[8]
print(new_key)
print(target_key)

['age_by_ds', 'creatinine_phosphokinase_by_ds', 'ejection_fraction_by_ds', 'serum_sodium_by_ds', 'serum_creatinine_by_ds', 'platelets_by_ds', 'time_by_ds']
DeathL


In [14]:
text_representation = tree.export_text(clf, feature_names=new_key)
print(text_representation)

|--- time_by_ds <= 0.50
|   |--- serum_sodium_by_ds <= 0.50
|   |   |--- creatinine_phosphokinase_by_ds <= 0.50
|   |   |   |--- serum_creatinine_by_ds <= 0.50
|   |   |   |   |--- class: 1
|   |   |   |--- serum_creatinine_by_ds >  0.50
|   |   |   |   |--- class: 1
|   |   |--- creatinine_phosphokinase_by_ds >  0.50
|   |   |   |--- ejection_fraction_by_ds <= 1.50
|   |   |   |   |--- class: 1
|   |   |   |--- ejection_fraction_by_ds >  1.50
|   |   |   |   |--- class: 0
|   |--- serum_sodium_by_ds >  0.50
|   |   |--- ejection_fraction_by_ds <= 0.50
|   |   |   |--- serum_sodium_by_ds <= 1.50
|   |   |   |   |--- class: 1
|   |   |   |--- serum_sodium_by_ds >  1.50
|   |   |   |   |--- class: 0
|   |   |--- ejection_fraction_by_ds >  0.50
|   |   |   |--- serum_sodium_by_ds <= 1.50
|   |   |   |   |--- class: 0
|   |   |   |--- serum_sodium_by_ds >  1.50
|   |   |   |   |--- class: 1
|--- time_by_ds >  0.50
|   |--- ejection_fraction_by_ds <= 0.50
|   |   |--- serum_creatinine_by_ds

In [16]:
from sklearn.tree import _tree

def tree_to_code(tree, feature_names):
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]
    feature_names = [f.replace(" ", "_")[:-5] for f in feature_names]
    print("def predict({}):".format(", ".join(feature_names)))

    def recurse(node, depth):
        indent = "    " * depth
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_name[node]
            threshold = tree_.threshold[node]
            print("{}if {} <= {}:".format(indent, name, np.round(threshold,2)))
            recurse(tree_.children_left[node], depth + 1)
            print("{}else:  # if {} > {}".format(indent, name, np.round(threshold,2)))
            recurse(tree_.children_right[node], depth + 1)
        else:
            print("{}return {}".format(indent, tree_.value[node]))

    recurse(0, 1)

In [17]:
def get_rules(tree, feature_names, class_names):
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]

    paths = []
    path = []
    
    def recurse(node, path, paths):
        
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_name[node]
            threshold = tree_.threshold[node]
            p1, p2 = list(path), list(path)
            p1 += [f"({name} <= {np.round(threshold, 3)})"]
            recurse(tree_.children_left[node], p1, paths)
            p2 += [f"({name} > {np.round(threshold, 3)})"]
            recurse(tree_.children_right[node], p2, paths)
        else:
            path += [(tree_.value[node], tree_.n_node_samples[node])]
            paths += [path]
            
    recurse(0, path, paths)

    # sort by samples count
    samples_count = [p[-1][1] for p in paths]
    ii = list(np.argsort(samples_count))
    paths = [paths[i] for i in reversed(ii)]
    
    rules = []
    for path in paths:
        rule = "if "
        
        for p in path[:-1]:
            if rule != "if ":
                rule += " and "
            rule += str(p)
        rule += " then "
        if class_names is None:
            rule += "response: "+str(np.round(path[-1][0][0][0],3))
        else:
            classes = path[-1][0][0]
            l = np.argmax(classes)
            rule += f"class: {class_names[l]} (proba: {np.round(100.0*classes[l]/np.sum(classes),2)}%)"
        rule += f" | based on {path[-1][1]:,} samples"
        rules += [rule]
    #print(class)
    return rules

In [18]:
print(len(target_key))

6


In [27]:
print(new_key)

['age_by_ds', 'creatinine_phosphokinase_by_ds', 'ejection_fraction_by_ds', 'serum_sodium_by_ds', 'serum_creatinine_by_ds', 'platelets_by_ds', 'time_by_ds']


In [20]:
rules = get_rules(clf, new_key,'01' )
for r in rules:
    print(r)

if (time_by_ds > 0.5) and (ejection_fraction_by_ds > 0.5) and (serum_creatinine_by_ds <= 1.5) and (age_by_ds <= 1.5) then class: 0 (proba: 97.94%) | based on 97 samples
if (time_by_ds <= 0.5) and (serum_sodium_by_ds > 0.5) and (ejection_fraction_by_ds > 0.5) and (serum_sodium_by_ds <= 1.5) then class: 0 (proba: 76.27%) | based on 59 samples
if (time_by_ds <= 0.5) and (serum_sodium_by_ds > 0.5) and (ejection_fraction_by_ds <= 0.5) and (serum_sodium_by_ds <= 1.5) then class: 1 (proba: 63.64%) | based on 33 samples
if (time_by_ds <= 0.5) and (serum_sodium_by_ds <= 0.5) and (creatinine_phosphokinase_by_ds <= 0.5) and (serum_creatinine_by_ds > 0.5) then class: 1 (proba: 91.67%) | based on 24 samples
if (time_by_ds > 0.5) and (ejection_fraction_by_ds <= 0.5) and (serum_creatinine_by_ds <= 0.5) and (time_by_ds > 1.5) then class: 0 (proba: 93.75%) | based on 16 samples
if (time_by_ds <= 0.5) and (serum_sodium_by_ds <= 0.5) and (creatinine_phosphokinase_by_ds <= 0.5) and (serum_creatinine_by_ds

In [21]:
l=['age_by_ds', 'creatinine_phosphokinase_by_ds', 'ejection_fraction_by_ds', 'serum_sodium_by_ds', 'serum_creatinine_by_ds', 'platelets_by_ds', 'time_by_ds','DeathL']

In [23]:
new_f=df[l]

In [25]:
(new_f)

age_by_ds  creatinine_phosphokinase_by_ds  ...  time_by_ds  DeathL
0            2                               0  ...           0       1
1            0                               2  ...           0       1
2            1                               0  ...           0       1
3            0                               0  ...           0       1
4            1                               0  ...           0       1
..         ...                             ...  ...         ...     ...
294          1                               0  ...           2       0
295          0                               1  ...           2       0
296          0                               1  ...           2       0
297          0                               1  ...           2       0
298          0                               0  ...           2       0

[299 rows x 8 columns]

In [26]:
new_f.to_csv('rule_ds.csv')